#ifndef MPATROL_DIPSWITCHES_H
#define MPATROL_DIPSWITCHES_H

// ==========================================================================
// mpatrol_dipswitches.h  --  GENERATED by tools/dipswitches/dipgen.py
// Source: `mame -listxml mpatrol`  (0.289 (mame0289))
//
// -listxml is MAME resolving the exact ioport this game's GAME/GAMEL line
// uses, after every PORT_INCLUDE / PORT_MODIFY -- so these values are the
// real ones for THIS set, not a hand-read of the wrong INPUT_PORTS block.
//
// Each <TAG>_DEFAULT below = OR of every dipvalue marked default="yes".
// 'Unused' switches (PORT_DIPUNUSED_DIPLOC) default to their bit SET, i.e.
// they read HIGH -- same as an unwired DIP line on real hardware.
//
// Re-run dipgen.py to regenerate. Hand-edit only the SELECTED #defines
// (below each switch) if you want a non-default machine configuration.
// ==========================================================================

// --------------------------------------------------------------------------
// DSW1   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW1:1+2  Lives  (bits 0x03)
//    1                            = 0x00
#define MPATROL_DSW1_LIVES_1                                 0x00
//    2                            = 0x01
#define MPATROL_DSW1_LIVES_2                                 0x01
//    3                            = 0x02   // default
#define MPATROL_DSW1_LIVES_3                                 0x02
//    5                            = 0x03
#define MPATROL_DSW1_LIVES_5                                 0x03
#define MPATROL_DSW1_LIVES_SELECTED                          MPATROL_DSW1_LIVES_3

//  DSW1:3+4  Bonus Life  (bits 0x0c)
//    10000 30000 50000            = 0x0c   // default
#define MPATROL_DSW1_BONUS_LIFE_10000_30000_50000            0x0c
//    20000 40000 60000            = 0x08
#define MPATROL_DSW1_BONUS_LIFE_20000_40000_60000            0x08
//    10000                        = 0x04
#define MPATROL_DSW1_BONUS_LIFE_10000                        0x04
//    None                         = 0x00
#define MPATROL_DSW1_BONUS_LIFE_NONE                         0x00
#define MPATROL_DSW1_BONUS_LIFE_SELECTED                     MPATROL_DSW1_BONUS_LIFE_10000_30000_50000

//  DSW1:5+6  Coin A  (bits 0x30)
//    3 Coins/1 Credit             = 0x10
#define MPATROL_DSW1_COIN_A_3_COINS_1_CREDIT                 0x10
//    2 Coins/1 Credit             = 0x20
#define MPATROL_DSW1_COIN_A_2_COINS_1_CREDIT                 0x20
//    1 Coin/1 Credit              = 0x30   // default
#define MPATROL_DSW1_COIN_A_1_COIN_1_CREDIT                  0x30
//    Free Play                    = 0x00
#define MPATROL_DSW1_COIN_A_FREE_PLAY                        0x00
#define MPATROL_DSW1_COIN_A_SELECTED                         MPATROL_DSW1_COIN_A_1_COIN_1_CREDIT

//  DSW1:5+6+7+8  Coinage  (bits 0xf0)
//    7 Coins/1 Credit             = 0x90
#define MPATROL_DSW1_COINAGE_7_COINS_1_CREDIT                0x90
//    6 Coins/1 Credit             = 0xa0
#define MPATROL_DSW1_COINAGE_6_COINS_1_CREDIT                0xa0
//    5 Coins/1 Credit             = 0xb0
#define MPATROL_DSW1_COINAGE_5_COINS_1_CREDIT                0xb0
//    4 Coins/1 Credit             = 0xc0
#define MPATROL_DSW1_COINAGE_4_COINS_1_CREDIT                0xc0
//    3 Coins/1 Credit             = 0xd0
#define MPATROL_DSW1_COINAGE_3_COINS_1_CREDIT                0xd0
//    2 Coins/1 Credit             = 0xe0
#define MPATROL_DSW1_COINAGE_2_COINS_1_CREDIT                0xe0
//    1 Coin/1 Credit              = 0xf0   // default
#define MPATROL_DSW1_COINAGE_1_COIN_1_CREDIT                 0xf0
//    1 Coin/2 Credits             = 0x70
#define MPATROL_DSW1_COINAGE_1_COIN_2_CREDITS                0x70
//    1 Coin/3 Credits             = 0x60
#define MPATROL_DSW1_COINAGE_1_COIN_3_CREDITS                0x60
//    1 Coin/4 Credits             = 0x50
#define MPATROL_DSW1_COINAGE_1_COIN_4_CREDITS                0x50
//    1 Coin/5 Credits             = 0x40
#define MPATROL_DSW1_COINAGE_1_COIN_5_CREDITS                0x40
//    1 Coin/6 Credits             = 0x30
#define MPATROL_DSW1_COINAGE_1_COIN_6_CREDITS                0x30
//    1 Coin/7 Credits             = 0x20
#define MPATROL_DSW1_COINAGE_1_COIN_7_CREDITS                0x20
//    1 Coin/8 Credits             = 0x10
#define MPATROL_DSW1_COINAGE_1_COIN_8_CREDITS                0x10
//    Free Play                    = 0x00
#define MPATROL_DSW1_COINAGE_FREE_PLAY                       0x00
#define MPATROL_DSW1_COINAGE_SELECTED                        MPATROL_DSW1_COINAGE_1_COIN_1_CREDIT

//  DSW1:7+8  Coin B  (bits 0xc0)
//    1 Coin/2 Credits             = 0xc0   // default
#define MPATROL_DSW1_COIN_B_1_COIN_2_CREDITS                 0xc0
//    1 Coin/3 Credits             = 0x80
#define MPATROL_DSW1_COIN_B_1_COIN_3_CREDITS                 0x80
//    1 Coin/5 Credits             = 0x40
#define MPATROL_DSW1_COIN_B_1_COIN_5_CREDITS                 0x40
//    1 Coin/6 Credits             = 0x00
#define MPATROL_DSW1_COIN_B_1_COIN_6_CREDITS                 0x00
#define MPATROL_DSW1_COIN_B_SELECTED                         MPATROL_DSW1_COIN_B_1_COIN_2_CREDITS

// DSW1 power-on byte (all switches at MAME default = 0xfe)
#define MPATROL_DSW1_DEFAULT ( \
  MPATROL_DSW1_LIVES_SELECTED | \
  MPATROL_DSW1_BONUS_LIFE_SELECTED | \
  MPATROL_DSW1_COIN_A_SELECTED | \
  MPATROL_DSW1_COINAGE_SELECTED | \
  MPATROL_DSW1_COIN_B_SELECTED   \
  )
// == 0xfe

// --------------------------------------------------------------------------
// DSW2   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW2:1  Flip Screen  (bits 0x01)
//    Off                          = 0x01   // default
#define MPATROL_DSW2_FLIP_SCREEN_OFF                         0x01
//    On                           = 0x00
#define MPATROL_DSW2_FLIP_SCREEN_ON                          0x00
#define MPATROL_DSW2_FLIP_SCREEN_SELECTED                    MPATROL_DSW2_FLIP_SCREEN_OFF

//  DSW2:2  Cabinet  (bits 0x02)
//    Upright                      = 0x00   // default
#define MPATROL_DSW2_CABINET_UPRIGHT                         0x00
//    Cocktail                     = 0x02
#define MPATROL_DSW2_CABINET_COCKTAIL                        0x02
#define MPATROL_DSW2_CABINET_SELECTED                        MPATROL_DSW2_CABINET_UPRIGHT

//  DSW2:3  Coin Mode  (bits 0x04)
//    Mode 1                       = 0x04   // default
#define MPATROL_DSW2_COIN_MODE_MODE_1                        0x04
//    Mode 2                       = 0x00
#define MPATROL_DSW2_COIN_MODE_MODE_2                        0x00
#define MPATROL_DSW2_COIN_MODE_SELECTED                      MPATROL_DSW2_COIN_MODE_MODE_1

//  DSW2:4  Unused  (bits 0x08)
//    Off                          = 0x08   // default
#define MPATROL_DSW2_UNUSED_OFF                              0x08
//    On                           = 0x00
#define MPATROL_DSW2_UNUSED_ON                               0x00
#define MPATROL_DSW2_UNUSED_SELECTED                         MPATROL_DSW2_UNUSED_OFF

//  DSW2:5  Stop Mode (Cheat)  (bits 0x10)
//    Off                          = 0x10   // default
#define MPATROL_DSW2_STOP_MODE_CHEAT_OFF                     0x10
//    On                           = 0x00
#define MPATROL_DSW2_STOP_MODE_CHEAT_ON                      0x00
#define MPATROL_DSW2_STOP_MODE_CHEAT_SELECTED                MPATROL_DSW2_STOP_MODE_CHEAT_OFF

//  DSW2:6  Sector Selection (Cheat)  (bits 0x20)
//    Off                          = 0x20   // default
#define MPATROL_DSW2_SECTOR_SELECTION_CHEAT_OFF              0x20
//    On                           = 0x00
#define MPATROL_DSW2_SECTOR_SELECTION_CHEAT_ON               0x00
#define MPATROL_DSW2_SECTOR_SELECTION_CHEAT_SELECTED         MPATROL_DSW2_SECTOR_SELECTION_CHEAT_OFF

//  DSW2:7  Invulnerability (Cheat)  (bits 0x40)
//    Off                          = 0x40   // default
#define MPATROL_DSW2_INVULNERABILITY_CHEAT_OFF               0x40
//    On                           = 0x00
#define MPATROL_DSW2_INVULNERABILITY_CHEAT_ON                0x00
#define MPATROL_DSW2_INVULNERABILITY_CHEAT_SELECTED          MPATROL_DSW2_INVULNERABILITY_CHEAT_OFF

//  DSW2:8  Service Mode  (bits 0x80)
//    Off                          = 0x80   // default
#define MPATROL_DSW2_SERVICE_MODE_OFF                        0x80
//    On                           = 0x00
#define MPATROL_DSW2_SERVICE_MODE_ON                         0x00
#define MPATROL_DSW2_SERVICE_MODE_SELECTED                   MPATROL_DSW2_SERVICE_MODE_OFF

// DSW2 power-on byte (all switches at MAME default = 0xfd)
#define MPATROL_DSW2_DEFAULT ( \
  MPATROL_DSW2_FLIP_SCREEN_SELECTED | \
  MPATROL_DSW2_CABINET_SELECTED | \
  MPATROL_DSW2_COIN_MODE_SELECTED | \
  MPATROL_DSW2_UNUSED_SELECTED | \
  MPATROL_DSW2_STOP_MODE_CHEAT_SELECTED | \
  MPATROL_DSW2_SECTOR_SELECTION_CHEAT_SELECTED | \
  MPATROL_DSW2_INVULNERABILITY_CHEAT_SELECTED | \
  MPATROL_DSW2_SERVICE_MODE_SELECTED   \
  )
// == 0xfd

#endif
