#!/usr/bin/env python3
"""
Simple ROM converter for Scregg.
Reads files from romszip/scregg_unpack and generates C header arrays
in src/machines/scregg/ named:
 - scregg_rom_main.h
 - scregg_chartiles.h
 - scregg_spritetiles.h
 - scregg_colorproms.h

This converter is intentionally conservative: it concatenates groups of
files into arrays in a common order; adjust the file order/constants if
you need to match exact MAME load offsets.
"""

import os
import sys
import zipfile

ROM_SET = os.path.normpath(os.path.join("..", "..", "romszip", "scregg.zip"))
OUT_DIR = os.path.normpath(os.path.join("..", "..", "source", "src", "machines", "scregg"))

def read_file(name):
    archive = zipfile.ZipFile(ROM_SET)
    try:
        data = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {ROM_SET}")
    return data

def write_c_array(path: Path, name: str, data: bytes, comment: str = ''):
    with open(path, 'w', newline='\n') as f:
        f.write(f"// Auto-generated by romconv/scregg/scregg_rom_convert.py - DO NOT EDIT\n")
        if comment:
            f.write(f"// {comment}\n")
        f.write(f"const unsigned char {name}[] = {"{"}\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            line = ','.join(f'0x{b:02X}' for b in chunk)
            f.write('  ' + line + ',\n')
        f.write('};\n')

# Group files heuristically
main_files =  ['scregg.a14','scregg.b14','scregg.c14','scregg.d14','scregg.e14']
gfx_files  =  ['scregg.g10','scregg.g12','scregg.h10','scregg.h12','scregg.j10','scregg.j12']
color_files = ['screggco.b4','screggco.c6']

main_files =  ["d40.a14", "d30.b14", "d20.c14", "d10.d14", "d00.e14"]
gfx_files  =  ["da0.g10", "d90.g12", "d80.h10", "d70.h12", "d60.j10", "d50.j12"]
color_files = ["db1.b4", "dc0.c6"]

# Read and concat if present
main_data = b''
for fn in main_files:
    main_data += read_file(fn)

gfx_data = b''
for fn in gfx_files:
    gfx_data += read_file(fn)

color_data = b''
for fn in color_files:
    color_data += read_file(fn)

# Write out headers
if main_data:
    write_c_array(os.path.join(OUT_DIR, 'scregg_rom.h'), 'scregg_rom', main_data, 'Scregg main CPU ROM (concatenated)')
else:
    print('No main ROM files found in', ROM_IN)

if gfx_data:
    write_c_array(os.path.join(OUT_DIR, 'scregg_chartiles.h'), 'scregg_chartiles', gfx_data, 'Scregg graphics data (concatenated)')
    write_c_array(os.path.join(OUT_DIR, 'scregg_spritetiles.h'), 'scregg_spritetiles', gfx_data, 'Scregg graphics data (duplicated for sprites)')

if color_data:
    write_c_array(os.path.join(OUT_DIR, 'scregg_colorprom.h'), 'scregg_colorprom', color_data, 'Scregg color PROMs')

print('Conversion complete. Headers written to', OUT_DIR)
